[pytest]
addopts = 
    -ra
    --strict-markers
    --disable-warnings
    --cov=src
    --cov=scripts
    --cov-report=term-missing

filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::FutureWarning
    ignore:.*TensorFlow.*:UserWarning
    ignore:.*Keras.*:UserWarning

testpaths = tests
